### ISSUE TITLE
bug: Hangs on large ppem (control-p) value

### ISSUE THREAD

**Issue by 100amps** [psb1558/ygt#11]
Press control-P to open the PPEM dialog box. Entering a stupidly large number in it will cause ygt to hang.  It probably just needs an input validation to confine input range to something reasonable.  I'm using Windows 11, python 3.11.x in case that matters.

**Comment by psb1558** [comment]
First of all, thanks for all the bug reports and feature requests. These are mostly on my to-do list (and I'll comment and close as I deal with them), except for this one. How big a value do you have to enter to hang the program? When I put in 500 ppem, it takes several seconds to generate the image--I suppose just because we're dealing with Python here and not C. If you put in, say, 10,000 ppem, it could easily take a minute or more.

It's pretty common to cut off hinting at 200 ppem. I could allow only up to, say, 400 ppem or whereever the user cuts off hinting, whichever is higher.

**Comment by 100amps** [comment]
The values I entered were 1200 and 2400. It may have just been processing, not hung, and I wasn't waiting long enough. I believe I waited about 10-15 seconds before killing it. I'll play with it more. 400 seems reasonable (famous last words).
