### ISSUE TITLE
Fit current glyph to window.

### ISSUE THREAD

**Issue by 100amps** [psb1558/ygt#8]
The original/default size of a glyph (control-0) is much larger than my current window size, and requires a few control-minus commands to zoom out and fit into the glyph window.  Ideally, a little "breathing room" around the glyph would be better than a tight fit of the glyph to the window size. If the Control-0 original size was planned to be an absolute size, the perhaps a command to "fit to window" would be appropriate.

I'm not sure if this behavior is expected or whether this is a bug.  If this behavior is unexpected, I am using Windows 11, Python 3.11.x.

<img width="1266" alt="screenfit" src="https://user-images.githubusercontent.com/18044808/233810367-bfe01830-5b49-475c-999d-0d3e7ad6cb6a.png">

**Comment by psb1558** [comment]
When displaying a glyph for the first time in a session:
- The glyph outline is sized to fill 80% of either the height or the width (as appropriate) of the edit pane, but
- The initial zoom factor is never more than 2.0.
- The glyph is centered in the edit pane until the user scrolls it.
- The program remembers the zoom factor for the glyph, so that's the value used when you revisit a glyph.
<img width="474" alt="image" src="https://user-images.githubusercontent.com/16215767/233998302-984ef8a7-68cf-4197-afe0-0c708a86ee89.png">
